/**
 * ALL_RULES.md renderer.
 * Emits every rule with full content, grouped by category and subcategory.
 *
 * @param {Array<{ rel: string, frontmatter?: any, content?: string }>} bundle
 * @returns {string}
 */
export function renderAllRules(bundle) {
  const items = (bundle ?? [])
    .map((item) => ({
      rel: normalizeRel(item.rel),
      content: normalizeLineEndings(String(item.content ?? "")),
    }))
    .filter((i) => i.rel && i.rel.endsWith(".mdc"))
    .sort((a, b) => a.rel.localeCompare(b.rel))

  const grouped = groupByCategoryAndSubcategory(items)

  const header = [
    "# ALL_RULES.md",
    "",
    "This file is auto-generated by `pnpm rules:compile`.",
    "Do not edit manually. Edit files in `/rules` and recompile.",
    "",
    "This file contains the full text of every rule, grouped by category and subcategory.",
    "",
  ].join("\n")

  const body = renderGrouped(grouped)

  return `${header}${body}`
}

function normalizeRel(rel) {
  const s = String(rel ?? "")
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
  // Defensive: drop any parent traversal segments to avoid weird output.
  return s.replace(/(^|\/)\.\.(?=\/|$)/g, "")
}

/** Normalize line endings to \\n for stable diffs and cross-platform consistency. */
function normalizeLineEndings(content) {
  return String(content ?? "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
}

/**
 * @param {Array<{ rel: string, content: string }>} items
 * @returns {Array<{ category: string, subgroups: Array<{ subcategory: string, rules: Array<{ rel: string, content: string }> }> }>}
 */
function groupByCategoryAndSubcategory(items) {
  /** @type {Record<string, Record<string, Array<{ rel: string, content: string }>>>} */
  const map = {}

  for (const item of items) {
    const parts = item.rel.split("/")
    const category = parts.length === 1 ? "root" : parts[0]
    const subcategory = parts.length >= 3 ? parts[1] : ""

    map[category] = map[category] ?? {}
    map[category][subcategory] = map[category][subcategory] ?? []
    map[category][subcategory].push(item)
  }

  // Build sorted output: root first, then alpha; within category sort subcats; within group sort rel.
  const categories = Object.keys(map).sort((a, b) => {
    if (a === "root") return -1
    if (b === "root") return 1
    return a.localeCompare(b)
  })

  return categories.map((category) => {
    const subcatMap = map[category]
    const subcategories = Object.keys(subcatMap).sort((a, b) => {
      // Keep empty subcategory first for readability (rules directly under category).
      if (a === "") return -1
      if (b === "") return 1
      return a.localeCompare(b)
    })

    const subgroups = subcategories.map((subcategory) => {
      const rules = subcatMap[subcategory].slice().sort((a, b) => a.rel.localeCompare(b.rel))
      return { subcategory, rules }
    })

    return { category, subgroups }
  })
}

/**
 * @param {ReturnType<typeof groupByCategoryAndSubcategory>} grouped
 * @returns {string}
 */
function renderGrouped(grouped) {
  /** @type {string[]} */
  const lines = []

  for (const { category, subgroups } of grouped) {
    lines.push(`## ${category}`)
    lines.push("")

    for (const { subcategory, rules } of subgroups) {
      if (subcategory) {
        lines.push(`### ${subcategory}`)
        lines.push("")
      }

      for (const rule of rules) {
        lines.push(`#### ${rule.rel}`)
        lines.push("")
        lines.push("```mdc")
        // Keep rule content verbatim; do not trim.
        lines.push(rule.content)
        // Ensure a newline before closing fence even if content doesn't end with one.
        if (!rule.content.endsWith("\n")) lines.push("")
        lines.push("```")
        lines.push("")
      }
    }
  }

  return lines.join("\n")
}
