const MAX_DESCRIPTION_CHARS = 140

/**
 * Index-only bootstrap renderer for CLAUDE.md.
 * Emits only references (path + short description). No rule bodies.
 *
 * @param {Array<{ rel: string, frontmatter: any, content: string }>} bundle
 * @param {{ maxChars?: number, includeShortSummary?: boolean }=} options
 * @returns {string}
 */
export function renderClaudeIndexOnly(bundle, options = {}) {
  const maxChars = typeof options.maxChars === "number" ? options.maxChars : 15_000

  const attempt = (includeShortSummary) => {
    const items = (bundle ?? [])
      .map((item) => ({
        rel: normalizeRel(item.rel),
        frontmatter: item.frontmatter ?? {},
        content: item.content ?? "",
      }))
      .filter((i) => i.rel && i.rel.endsWith(".mdc"))
      .sort((a, b) => a.rel.localeCompare(b.rel))

    const groups = groupByTopSegment(items)

    const header = [
      "# CLAUDE.md",
      "",
      "This file is auto-generated by `pnpm rules:compile`.",
      "Do not edit manually. Edit files in `/rules` and recompile.",
      "",
      "## Tiers",
      "",
      "- Tier 0: this file (index-only).",
      "- Tier 1/2: full rules in `.claude/rules/` (loaded on demand).",
      "",
      "## How to use (bootstrap)",
      "",
      "- Use `@rules/<path>.mdc` references (or your local tag conventions) to load full rule content on demand.",
      "- Full rule content is synced to `.claude/rules/` and also exists in the project rule sources.",
      "- Keep this file lean: it is always loaded and impacts performance.",
      "",
    ].join("\n")

    const router = renderRouter(groups, { includeShortSummary })
    return `${header}\n${router}\n`
  }

  const requested = options.includeShortSummary === true
  const primary = attempt(requested)

  if (primary.length <= maxChars) return primary

  if (requested) {
    const downgraded = attempt(false)
    if (downgraded.length <= maxChars) return downgraded
  }

  throw new Error(
    `CLAUDE.md exceeded size budget: ${primary.length} > ${maxChars} chars. ` +
      "Reduce descriptions/summaries or increase maxChars.",
  )
}

function normalizeRel(rel) {
  return String(rel ?? "")
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
}

function groupByTopSegment(items) {
  /** @type {Record<string, Array<any>>} */
  const map = {}
  for (const item of items) {
    const parts = item.rel.split("/")
    const seg = parts.length === 1 && item.rel.endsWith(".mdc") ? "entrypoints" : parts[0]
    map[seg] = map[seg] ?? []
    map[seg].push(item)
  }
  return map
}

function renderRouter(groups, { includeShortSummary }) {
  const segments = Object.keys(groups).sort((a, b) => {
    if (a === "entrypoints") return -1
    if (b === "entrypoints") return 1
    return a.localeCompare(b)
  })

  const lines = [
    "## Rules index (router)",
    "",
    "Each entry points to the source rule file. Content is intentionally not inlined here.",
    "",
  ]

  for (const seg of segments) {
    lines.push(`### ${seg}`)
    lines.push("")

    for (const item of groups[seg]) {
      const description = getOneLineDescription(item, { includeShortSummary })
      lines.push(`- \`@rules/${item.rel}\` — ${description}`)
    }

    lines.push("")
  }

  return lines.join("\n")
}

function getOneLineDescription(item, { includeShortSummary }) {
  const fm = item.frontmatter ?? {}
  const fromFrontmatter = toOneLine(fm.description || fm.overview || fm.title || fm.name || "")

  const raw = (() => {
    if (!includeShortSummary) return fromFrontmatter
    const fromBody = toOneLine(extractShortSummaryLine(item.content))
    return fromFrontmatter || fromBody
  })()

  const safe = raw || "No description provided."
  return truncate(safe, MAX_DESCRIPTION_CHARS)
}

function truncate(value, max) {
  if (value.length <= max) return value
  const cut = value.slice(0, max - 1)
  const lastSpace = cut.lastIndexOf(" ")
  const safe = lastSpace > 40 ? cut.slice(0, lastSpace) : cut
  return `${safe}…`
}

function toOneLine(value) {
  const s = String(value || "").trim()
  if (!s) return ""
  return s.replace(/\s+/g, " ")
}

function extractShortSummaryLine(content) {
  const text = String(content || "")

  // JS does not support \z. Use end-of-string via $ with a safe alternation.
  const match = text.match(/##\s+Short summary\s*\n([\s\S]*?)(?=\n##\s|\n#\s|$)/i)
  if (!match) return ""

  const block = match[1] || ""
  const lines = block
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)

  const bullet = lines.find((l) => l.startsWith("- ") || l.startsWith("* "))
  if (bullet) return bullet.replace(/^[-*]\s+/, "")

  return lines[0] || ""
}
