import { renderIndexOnly } from "./renderIndexOnly.mjs"

const GEMINI_HEADER_INTRO = [
  "This file is auto-generated by `pnpm rules:compile`.",
  "Do not edit manually. Edit files in `src/rules` and recompile.",
  "",
  "## Index-only",
  "",
  "This file lists rule references only. Content is not inlined.",
  "Use `@rules/<path>.mdc` to load full rule content.",
  "If your IDE does not resolve @rules/... references, ensure rules are synced to your IDE config.",
].join("\n")

const GEMINI_MAX_CHARS = 50_000

/**
 * @param {{ frontmatter: object }} item
 * @returns {string}
 */
function getActivation(item) {
  const { frontmatter } = item
  if (frontmatter.alwaysApply === true) return "Always On"
  if (frontmatter.globs && frontmatter.globs.trim() !== "") return `Glob: ${frontmatter.globs}`
  return "Model Decision"
}

/**
 * Render bundle as GEMINI.md (index-only with optional activation badges).
 *
 * @param {Array<{ rel: string, frontmatter: object, content: string }>} bundle - From generateBundle
 * @returns {string} - Rendered GEMINI.md content
 */
export function renderAntigravity(bundle) {
  return renderIndexOnly(bundle, {
    format: "claude",
    title: "# GEMINI.md",
    headerIntro: GEMINI_HEADER_INTRO,
    maxChars: GEMINI_MAX_CHARS,
    includeShortSummary: true,
    referencePrefix: "@rules/",
    onLimit: "error",
    getRuleBadges: (item) => [getActivation(item)],
  })
}
