import { renderIndexOnly } from "./renderIndexOnly.mjs"

const CLAUDE_HEADER_INTRO = [
  "This file is auto-generated by `pnpm rules:compile`.",
  "Do not edit manually. Edit files in `/rules` and recompile.",
  "",
  "## Tiers",
  "",
  "- Tier 0: this file (index-only).",
  "- Tier 1/2: full rules in `.claude/rules/` (loaded on demand).",
  "",
  "## How to use (bootstrap)",
  "",
  "- Use `@rules/<path>.mdc` references (or your local tag conventions) to load full rule content on demand.",
  "- Full rule content is synced to `.claude/rules/` and also exists in the project rule sources.",
  "- Keep this file lean: it is always loaded and impacts performance.",
].join("\n")

/**
 * Index-only bootstrap renderer for CLAUDE.md.
 * Thin wrapper around renderIndexOnly with CLAUDE-specific header and options.
 *
 * @param {Array<{ rel: string, frontmatter: any, content: string }>} bundle
 * @param {{ maxChars?: number, includeShortSummary?: boolean }=} options
 * @returns {string}
 */
export function renderClaudeIndexOnly(bundle, options = {}) {
  const maxChars = typeof options.maxChars === "number" ? options.maxChars : 15_000
  return renderIndexOnly(bundle, {
    format: "claude",
    title: "# CLAUDE.md",
    headerIntro: CLAUDE_HEADER_INTRO,
    maxChars,
    includeShortSummary: options.includeShortSummary === true,
    referencePrefix: "@rules/",
    onLimit: "error",
  })
}
