import { renderIndexOnly } from "./renderIndexOnly.mjs"
import { detectUmbrellaType } from "./antigravity/detectUmbrellaType.mjs"

const GEMINI_HEADER_INTRO = [
  "This file is auto-generated by `pnpm rules:compile`.",
  "Do not edit manually. Edit files in `src/rules` and recompile.",
  "",
  "## Index-only",
  "",
  "This file lists rule references only. Content is not inlined.",
  "Use `@.agent/rules/*.md` and `@.agent/workflows/*.md` to load synced Antigravity content.",
  "If your IDE does not resolve these references, ensure rules are synced to `~/.gemini/.agent/`.",
].join("\n")

const GEMINI_MAX_CHARS = 50_000

/**
 * @param {{ frontmatter: object }} item
 * @returns {string}
 */
function getActivation(item) {
  const { frontmatter } = item
  if (frontmatter.alwaysApply === true) return "Always On"
  if (frontmatter.globs && frontmatter.globs.trim() !== "") return `Glob: ${frontmatter.globs}`
  return "Model Decision"
}

function getAntigravityReference(item) {
  const ruleName = item.rel.replace(/\.mdc$/, "").replace(/\//g, "-")
  const { isWorkflow } = detectUmbrellaType(
    {
      frontmatter: item.frontmatter,
      content: item.content,
    },
    item.rel,
  )

  return isWorkflow ? `@.agent/workflows/${ruleName}.md` : `@.agent/rules/${ruleName}.md`
}

/**
 * Render bundle as GEMINI.md (index-only with optional activation badges).
 *
 * @param {Array<{ rel: string, frontmatter: object, content: string }>} bundle - From generateBundle
 * @returns {string} - Rendered GEMINI.md content
 */
export function renderAntigravity(bundle) {
  return renderIndexOnly(bundle, {
    format: "claude",
    title: "# GEMINI.md",
    headerIntro: GEMINI_HEADER_INTRO,
    maxChars: GEMINI_MAX_CHARS,
    includeShortSummary: true,
    getRuleRef: getAntigravityReference,
    onLimit: "error",
    getRuleBadges: (item) => [getActivation(item)],
  })
}
